### ISSUE TITLE
Cannot Make Error 2

### ISSUE THREAD

**Issue by mkylasoto** [ulli-kroll/rtl8812bu#12]
When trying to build on Kali Linux kernel 4.19 I get the error in the following log: 
root@kali:~/Desktop/rtl8822bu-master# make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.19.0-kali4-amd64/build M=/root/Desktop/rtl8822bu-master modules
make[1]: Entering directory '/usr/src/linux-headers-4.19.0-kali4-amd64'
  CC [M]  /root/Desktop/rtl8822bu-master/core/rtw_cmd.o
In file included from /root/Desktop/rtl8822bu-master/include/osdep_service.h:41,
                 from /root/Desktop/rtl8822bu-master/include/drv_types.h:32,
                 from /root/Desktop/rtl8822bu-master/core/rtw_cmd.c:22:
/root/Desktop/rtl8822bu-master/include/osdep_service_linux.h: In function ‘_init_timer’:
/root/Desktop/rtl8822bu-master/include/osdep_service_linux.h:257:8: error: ‘_timer’ {aka ‘struct timer_list’} has no member named ‘data’
  ptimer->data = (unsigned long)cntx;
        ^~
/root/Desktop/rtl8822bu-master/include/osdep_service_linux.h:258:2: error: implicit declaration of function ‘init_timer’; did you mean ‘_init_timer’? [-Werror=implicit-function-declaration]
  init_timer(ptimer);
  ^~~~~~~~~~
  _init_timer
In file included from /root/Desktop/rtl8822bu-master/include/drv_types.h:35,
                 from /root/Desktop/rtl8822bu-master/core/rtw_cmd.c:22:
/root/Desktop/rtl8822bu-master/include/wifi.h: At top level:
/root/Desktop/rtl8822bu-master/include/wifi.h:1005: warning: "IEEE80211_MAX_AMPDU_BUF" redefined
 #define IEEE80211_MAX_AMPDU_BUF 0x40
 
In file included from /root/Desktop/rtl8822bu-master/include/osdep_service_linux.h:84,
                 from /root/Desktop/rtl8822bu-master/include/osdep_service.h:41,
                 from /root/Desktop/rtl8822bu-master/include/drv_types.h:32,
                 from /root/Desktop/rtl8822bu-master/core/rtw_cmd.c:22:
/usr/src/linux-headers-4.19.0-kali4-common/include/linux/ieee80211.h:1442: note: this is the location of the previous definition
 #define IEEE80211_MAX_AMPDU_BUF  0x100
 
cc1: some warnings being treated as errors
make[4]: *** [/usr/src/linux-headers-4.19.0-kali4-common/scripts/Makefile.build:309: /root/Desktop/rtl8822bu-master/core/rtw_cmd.o] Error 1
make[3]: *** [/usr/src/linux-headers-4.19.0-kali4-common/Makefile:1535: _module_/root/Desktop/rtl8822bu-master] Error 2
make[2]: *** [Makefile:146: sub-make] Error 2
make[1]: *** [Makefile:8: all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.19.0-kali4-amd64'
make: *** [Makefile:1318: modules] Error 2

Does anyone know a fix??

**Comment by ulli-kroll** [comment]
Maybe your kernel source is not prepared.

AND don't compile as user **root**
